### ISSUE TITLE
error: how to make it work with passenger?

### ISSUE THREAD

**Issue by juergengunz** [pofider/phantom-workers#14]
if i use phantom workers i am always getting an error and it crashes my node server

`Trace: You required the Node Cluster module, which is incompatible with Passenger, a non-functional shim was returned and your app may still work. However, please remove the related code as soon as possible.
App 7176 stderr:     at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:63:12)
App 7176 stderr:     at require (internal/module.js:20:19)
App 7176 stderr:     at Object.<anonymous> (/var/www/vhosts/holmi.at/api.holmi.at/node_modules/phantom-workers/lib/phantomManager.js:12:15)
App 7176 stderr:     at Module._compile (module.js:570:32)
App 7176 stderr:     at Object.Module._extensions..js (module.js:579:10)
App 7176 stderr:     at Module.load (module.js:487:32)
App 7176 stderr:     at tryModuleLoad (module.js:446:12)
App 7176 stderr:     at Function.Module._load (module.js:438:3)
App 7176 stderr:     at Module.require (module.js:497:17)
App 7176 stderr:     at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25)
App 7176 stderr:     at require (internal/module.js:20:19)
App 7176 stderr:     at Object.<anonymous> (/var/www/vhosts/holmi.at/api.holmi.at/node_modules/phantom-workers/index.js:6:33)
App 7176 stderr:     at Module._compile (module.js:570:32)
App 7176 stderr:     at Object.Module._extensions..js (module.js:579:10)
App 7176 stderr:     at Module.load (module.js:487:32)
App 7176 stderr:     at tryModuleLoad (module.js:446:12)
`

**Comment by pofider** [comment]
Hm. We use cluster to find a free port for the phantomjs web server.
Isn't there a way to run cluster module in passenger? I've never use it.

**Comment by juergengunz** [comment]
as far as I know, cluster is not working along with passenger. PDFs are created and working but it throws this error and you have to restart the node server to make it working again...

Is there a way to use the module without the cluster?

**Comment by bjrmatos** [comment]
the passenger that you're talking about is [this](https://www.phusionpassenger.com/) right? 

> as far as I know, cluster is not working along with passenger. 

yes, this is true according to their docs.

<img width="772" alt="captura de pantalla 2017-11-27 a las 1 18 50 p m" src="https://user-images.githubusercontent.com/4262050/33282110-9cb3fb04-d375-11e7-9585-becbd529b29d.png">

seems like passenger replaces the need for cluster, pm2, forever. but we are just reading a property available in `cluster` module -> `cluster.worker` not creating servers or something, i don't know why passenger does forbid simple usages like this.

so at this point to answer the original question, it seems like `phantom-workers` can not work when using `passenger`, this is because `passenger` limitations. 

if you want support for this, i think you should talk with passenger's support channels and ask questions about it or even better make a pull request in this module that adds support for it (if you find the way to make it work).

**Comment by bjrmatos** [comment]
i've closed the issue to keep things clean in the repository, but feel free to add comments to the conversation.

**Comment by juergengunz** [comment]
@bjrmatos  you are right - thank's for your help. I ended up using the node-html-pdf module which is working fine with passenger

**Comment by bjrmatos** [comment]
@juergengunz nice that you find a solution. also be aware that if you use [phantom-html-to-pdf](https://github.com/pofider/phantom-html-to-pdf) with `dedicated-process` strategy it should work fine in passenger (there is no cluster involved). just FYI (don't know if you tried that before).

**Comment by juergengunz** [comment]
@bjrmatos I used (phantom-html-to-pdf) before and this module is using this (phantom-workers) module, therefore it is not compatible with passenger..

**Comment by bjrmatos** [comment]
if you use `dedicated-process` strategy, phantom-workers is not required in the process.

```js
var conversion = require("phantom-html-to-pdf")({
	/*other options here*/
	strategy: "dedicated-process",
	/*other options here*/
});
```

**Comment by bjrmatos** [comment]
you're probably not specifying any `strategy` option, so it uses the default which is `phantom-server`, which requires `phantom-workers`. but if you use `dedicated-process` you won't be using phantom-workers at all in your node process, so it should work in passenger normally. again just FYI
